version: '3.8'

services:
  # Airflow components
  airflow-webserver:
    image: apache/airflow:2.5.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW_VAR_manh_base_url=${MANH_BASE_URL}
      - AIRFLOW_VAR_manh_client_id=${MANH_CLIENT_ID}
      - AIRFLOW_VAR_manh_client_secret=${MANH_CLIENT_SECRET}
      - AIRFLOW_VAR_organization_list=${ORGANIZATION_LIST}
      - AIRFLOW_VAR_s3_data_bucket=${S3_DATA_BUCKET}
      - AIRFLOW_VAR_slack_webhook_url=${SLACK_WEBHOOK_URL}
      - AIRFLOW_VAR_alert_email_recipients=${ALERT_EMAIL_RECIPIENTS}
      - AIRFLOW_VAR_dashboard_url=${DASHBOARD_URL}
      - AIRFLOW_CONN_redis_default=redis://:@redis:6379/0
      - AIRFLOW_CONN_aws_default=aws://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@?region_name=${AWS_REGION}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  airflow-scheduler:
    image: apache/airflow:2.5.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_VAR_manh_base_url=${MANH_BASE_URL}
      - AIR